// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1BWY_-ENV9r3lY1QiHmb9sOJtSGojizk',
    appId: '1:916927144859:web:9b94ea514e235a73f8773e',
    messagingSenderId: '916927144859',
    projectId: 'cinesync-ffcb9',
    authDomain: 'cinesync-ffcb9.firebaseapp.com',
    storageBucket: 'cinesync-ffcb9.firebasestorage.app',
    measurementId: 'G-PWCMKHQJP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXmpAtpf2B3RmXkz1StrXy-Bah0iIrIB4',
    appId: '1:916927144859:android:940eaccbc94d6747f8773e',
    messagingSenderId: '916927144859',
    projectId: 'cinesync-ffcb9',
    storageBucket: 'cinesync-ffcb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1VMR2DhzM4d4Uhu5rpVQlZqiweIr1vE',
    appId: '1:916927144859:ios:e1eb88d315057ff4f8773e',
    messagingSenderId: '916927144859',
    projectId: 'cinesync-ffcb9',
    storageBucket: 'cinesync-ffcb9.firebasestorage.app',
    iosBundleId: 'com.cinesync.cinesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ1VMR2DhzM4d4Uhu5rpVQlZqiweIr1vE',
    appId: '1:916927144859:ios:e1eb88d315057ff4f8773e',
    messagingSenderId: '916927144859',
    projectId: 'cinesync-ffcb9',
    storageBucket: 'cinesync-ffcb9.firebasestorage.app',
    iosBundleId: 'com.cinesync.cinesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1BWY_-ENV9r3lY1QiHmb9sOJtSGojizk',
    appId: '1:916927144859:web:0f775a80765337e9f8773e',
    messagingSenderId: '916927144859',
    projectId: 'cinesync-ffcb9',
    authDomain: 'cinesync-ffcb9.firebaseapp.com',
    storageBucket: 'cinesync-ffcb9.firebasestorage.app',
    measurementId: 'G-Z76DMY1CEW',
  );
}
